# 1. Lecture du fichier CSV

In [2]:
import pandas as pd

csv_path = "../data/student-mat.csv"
df = pd.read_csv(csv_path, sep=";")
print("Aperçu des données CSV :")
display(df.head())
print("\nInformations sur le dataset CSV :")
df.info()

Aperçu des données CSV :

   StudentID school sex  age  G1  G2  G3
0          1     GP   F   18  10  11  12
1          2     GP   M   17  12  13  14
2          3     GP   F   15  14  15  16
3          4     GP   M   16  15  16  17
4          5     GP   F   17  16  17  18

Informations sur le dataset CSV :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  20 non-null     int64
 1   school     20 non-null     object
 2   sex        20 non-null     object
 3   age        20 non-null     int64
 4   G1         20 non-null     int64
 5   G2         20 non-null     int64
 6   G3         20 non-null     int64
dtypes: int64(5), object(2)
memory usage: 1.2+ KB

# 2. Lecture du fichier JSON

In [3]:
import pandas as pd

json_path = "../data/movies.json"
movies = pd.read_json(json_path)
print("\nAperçu des données JSON :")
display(movies.head())

Aperçu des données JSON :

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,Country,Awards,Poster,Metascore,imdbRating,imdbVotes,imdbID,Type,Response,Images
0,Avatar,2009,PG-13,18 Dec 2009,162 min,"Action, Adventure, Fantasy",James Cameron,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...",A paraplegic marine dispatched to the moon Pan...,...,"USA, UK",Won 3 Oscars. Another 80 wins & 121 nominations.,http://ia.media-imdb.com/images/M/MV5BMTYwOTEw...,83,7.9,"890,617",tt0499549,movie,True,[https://images-na.ssl-images-amazon.com/image...
1,I Am Legend,2007,PG-13,14 Dec 2007,101 min,"Drama, Horror, Sci-Fi",Francis Lawrence,"Mark Protosevich (screenplay), Akiva Goldsman ...","Will Smith, Alice Braga, Charlie Tahan, Salli ...",Years after a plague kills most of humanity an...,...,USA,9 wins & 21 nominations.,http://ia.media-imdb.com/images/M/MV5BMTU4NzMy...,65,7.2,"533,874",tt0480249,movie,True,[https://images-na.ssl-images-amazon.com/image...

# 3. Lecture du fichier Excel

In [4]:
import pandas as pd

excel_path = "../data/DataProjet.xlsx"
DataProjet = pd.read_excel(excel_path, skiprows=5, usecols="B:H")
print("\nAperçu des données Excel :")
display(DataProjet.head())

Aperçu des données Excel :

,Project Name,Task Name,Assigned to,Start Date,Days Required,End Date,Progress
0,Marketing,Market Research,Alice,2024-01-01,13,2024-01-14,0.78
1,Marketing,Content Creation,Bob,2024-01-14,14,2024-01-28,1.00
2,Marketing,Social Media Planning,Charlie,2024-01-28,22,2024-02-19,0.45
3,Marketing,Campaign Analysis,Daisy,2024-02-18,25,2024-03-14,0.00
4,Product Dev,Prototype Development,Ethan,2024-01-02,18,2024-01-20,1.00

# 4. Connexion à la base de données MySQL

In [6]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("mysql+pymysql://root:@localhost/school_db")
query = "SELECT * FROM student_mat WHERE G3 > 15"
df_top_students = pd.read_sql(query, engine)
print("\nTop students (G3 > 15) :")
display(df_top_students.head())

Top students (G3 > 15) :

   StudentID school sex  age  G1  G2  G3
0          3     GP   F   15  14  15  16
1          4     GP   M   16  15  16  17
2          5     GP   F   17  16  17  18
3         10     GP   M   17  14  15  16
4         13     GP   F   15  14  15  16

# 5. Lecture du fichier robots.txt

In [7]:
import requests

base_url = "https://books.toscrape.com/"
robots_url = base_url + "robots.txt"
response_robots = requests.get(robots_url)
print("\nrobots.txt :")
if response_robots.status_code == 200:
    print(response_robots.text)
else:
    print("robots.txt : not found")

robots.txt :
robots.txt : not found

# 6. Web scraping des titres de livres

In [9]:
import requests
from bs4 import BeautifulSoup

base_url = "https://books.toscrape.com/"
page = requests.get(base_url)
soup = BeautifulSoup(page.content, 'html.parser')
titles = soup.find_all('h3')
print("\n5 premiers titres de livres :")
for title in titles[:5]:
    book_name = title.select_one('a').get('title')
    print(f"- {book_name}")

5 premiers titres de livres :
- A Light in the Attic
- Tipping the Velvet
- Soumission
- Sharp Objects
- Sapiens: A Brief History of Humankind

# 7. Consommation d'une API et conversion en DataFrame

In [10]:
import requests
import pandas as pd

api_url = "https://jsonplaceholder.typicode.com/users"
response_api = requests.get(api_url)
data_json = response_api.json()
df_users = pd.DataFrame(data_json)
print("\nAperçu des utilisateurs de l'API :")
display(df_users[['id', 'name', 'username', 'email', 'phone']].head())

Aperçu des utilisateurs de l'API :

,id,name,username,email,phone
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289